[package]
name = "horsenuggets/luau-futures"
description = "Rust-like futures for Luau"
version = "2.0.0-beta.4"
license = "MIT"
authors = ["YetAnotherClown"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
repository = "https://github.com/horsenuggets/luau-futures"
include = [
    "default.project.json",
    "LICENSE",
    "README.md",
    "init.luau",
    "src",
    "wally.toml",
]
exclude = ["**"]

[dev-dependencies]
Testable = "horsenuggets/testable@0.1.0"
